backend:
  name: git-gateway
  branch: main
locale: fr

media_folder: "assets/images/uploads"   # Emplacement des images uploadées
public_folder: "/assets/images/uploads"   # Chemin public

collections:
  - name: "actualites"
    label: "Actualités"
    folder: "content/actualites"
    create: true
    format: json
    fields:
      - { name: "title", label: "Titre", widget: "string" }
      - { name: "body", label: "Contenu", widget: "markdown" }
      - { name: "image", label: "Image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "À la une", name: "highlight", widget: "boolean", default: false }

  - name: "convocations"
    label: "Convocations"
    folder: "content/convocations"
    create: true
    format: json
    slug: "convocation-{{year}}-{{month}}-{{day}}"
    fields:
      - { name: "equipe", label: "Équipe (ex: U7, U9, U14)", widget: "string" }
      - { name: "match_title", label: "Titre du match", widget: "string" }
      - { name: "match_date", label: "Date du match", widget: "string", hint: "Ex : 12 septembre 2025" }
      - { name: "match_time", label: "Heure du match", widget: "string", hint: "Ex : 20h00" }
      - label: "Liste des joueurs"
        name: "joueurs"
        widget: "list"
        summary: "{{nom}} - Convoqué : {{convoque}}"
        fields:
          - { name: "nom", label: "Nom du joueur", widget: "string" }
          - { name: "convoque", label: "Convoqué ?", widget: "select", options: ["Oui", "Non"], default: "Non" }



  - name: "galerie"
    label: "Galerie"
    folder: "content/galerie"
    create: true
    format: json
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Titre du match", widget: "string" }
      - { name: "resume", label: "Résumé du match", widget: "markdown" }
      - { 
          name: "photos", 
          label: "Photos", 
          widget: "list", 
          field: { name: "photo", label: "Photo", widget: "image" } 
        }

  - name: "calendrier"
    label: "Calendrier / Matchs"
    folder: "content/calendrier"
    create: true
    format: json
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - { name: "title", label: "Titre", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
  
  - name: "objets_trouves"
    label: "Objets trouvés"
    folder: "content/objets-trouves"
    create: true
    format: json
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Titre", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Photo", widget: "image" }

  - name: "partenaires"
    label: "Partenaires"
    folder: "content/partenaires"
    create: true
    format: json
    slug: "{{slug}}"
    fields:
      - { name: "nom", label: "Nom du partenaire", widget: "string" }
      - { name: "logo", label: "Logo", widget: "image" }
      - { name: "description", label: "Description", widget: "text" }
  
