name: Mirror backup to private repo

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config --global user.name "Backup Bot"
          git config --global user.email "bot@users.noreply.github.com"

            - name: Add backup remote
        env:
          BACKUP_TOKEN: ${{ secrets.BACKUP_TOKEN }}
        run: |
          set -e
          git remote add backup https://x-access-token:${BACKUP_TOKEN}@github.com/fredchanu/club-foot-la-selle-la-forge-backup.git
          git remote -v

      - name: Test auth to backup (ls-remote)
        env:
          BACKUP_TOKEN: ${{ secrets.BACKUP_TOKEN }}
        run: |
          git ls-remote https://x-access-token:${BACKUP_TOKEN}@github.com/fredchanu/club-foot-la-selle-la-forge-backup.git

      - name: Mirror push (all refs)
        run: |
          git push --mirror --prune backup

